FROM --platform=linux/amd64 python:3.10-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /code

# Install dependencies in one layer to reduce image size
RUN apt-get update && \
    apt-get install -y --no-install-recommends netcat-traditional gettext httpie && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir --upgrade pip flask

# Copy just the server.py file
COPY ./server.py /code/

EXPOSE 5000

ENTRYPOINT ["python", "./server.py"]