# Generated by Django 4.1.3 on 2025-01-15 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0005_alter_customer_user_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
