# Generated by Django 4.1.3 on 2025-01-16 04:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0007_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuFood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_name', models.CharField(max_length=100)),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodtype', to='GrabFood.typefood')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menu', to='GrabFood.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
