# Generated by Django 4.1.3 on 2025-01-16 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0008_typefood_menufood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menufood',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menu', to='GrabFood.restaurant'),
        ),
    ]
