# Generated by Django 4.1.3 on 2025-01-16 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0009_alter_menufood_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid phone number with exactly 10 digits')]),
        ),
    ]
