# Generated by Django 4.1.3 on 2025-01-17 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0011_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ReviewMenu',
        ),
    ]
