# Generated by Django 4.1.3 on 2025-01-17 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0012_rename_review_reviewmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmenu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 17, 10, 5, 57, 393348, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewmenu',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2025, 1, 17, 10, 6, 17, 277627, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
