# Generated by Django 4.1.3 on 2025-01-17 10:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0013_reviewmenu_created_at_reviewmenu_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('cccd', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Enter a valid phone number with exactly 12 digits')])),
                ('license_plate', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[A-Z0-9 -]{5,15}$', 'Enter a valid license plate')])),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('vehicle', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipper_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
