# Generated by Django 5.1.5 on 2025-01-21 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0017_alter_user_email'),
        ('GrabFood', '0018_alter_user_email'),
    ]

    operations = [
    ]
