# Generated by Django 5.1.5 on 2025-02-18 01:38

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0019_merge_0017_alter_user_email_0018_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1, help_text='Số lượng món ăn đã đặt trong lịch sử.', validators=[django.core.validators.MinValueValidator(1)])),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.expressions.Case, related_name='customer_history', to='GrabFood.customer')),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_history', to='GrabFood.menufood')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
