# Generated by Django 5.1.5 on 2025-02-24 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0020_alter_user_email_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('customer', models.ManyToManyField(related_name='customuser_favouritemenu', to='GrabFood.customer')),
                ('menu', models.ManyToManyField(related_name='menu_favouritemenu', to='GrabFood.menufood')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
