# Generated by Django 5.1.5 on 2025-03-10 08:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0021_favoritemenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('minimum_order_value', models.IntegerField()),
                ('expiration_date', models.DateTimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_voucer', to='GrabFood.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
