# Generated by Django 5.1.5 on 2025-04-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0024_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='images/default-ui-image-placeholder-wireframes-600nw-1037719192.webp', upload_to='images/'),
        ),
    ]
