# Generated by Django 5.1.5 on 2025-04-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0025_alter_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menufood',
            name='image',
            field=models.ImageField(default='images/default-ui-image-placeholder-wireframes-600nw-1037719192.webp', upload_to='images/'),
        ),
    ]
