# Generated by Django 5.1.5 on 2025-05-06 04:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0026_menufood_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=cloudinary.models.CloudinaryField(default='images/default-ui-image-placeholder-wireframes-600nw-1037719192.webp', max_length=255, verbose_name='image'),
        ),
    ]
