# Generated by Django 5.1.5 on 2025-05-11 06:04

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0027_alter_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='typefood',
            name='image',
            field=cloudinary.models.CloudinaryField(default='images/default-ui-image-placeholder-wireframes-600nw-1037719192.webp', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='menufood',
            name='image',
            field=cloudinary.models.CloudinaryField(default='images/default-ui-image-placeholder-wireframes-600nw-1037719192.webp', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='GrabFood.restaurant'),
        ),
    ]
