# Generated by Django 5.1.5 on 2025-05-11 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0028_typefood_image_alter_menufood_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menufood',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menufood',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=100)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_option', to='GrabFood.menufood')),
            ],
        ),
        migrations.AddField(
            model_name='menufood',
            name='option',
            field=models.ManyToManyField(blank=True, to='GrabFood.option'),
        ),
    ]
