# Generated by Django 5.1.5 on 2025-05-11 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0029_menufood_description_menufood_time_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
