# Generated by Django 5.1.5 on 2025-05-11 07:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0030_alter_option_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('option_name', models.CharField(max_length=100)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_menu', to='GrabFood.menufood')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='menufood',
            name='option',
            field=models.ManyToManyField(blank=True, to='GrabFood.optionmenu'),
        ),
    ]
