# Generated by Django 5.1.5 on 2025-05-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0031_optionmenu_alter_menufood_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menufood',
            name='option',
        ),
    ]
