# Generated by Django 5.1.5 on 2025-05-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0032_remove_menufood_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionmenu',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
