# Generated by Django 5.1.5 on 2025-05-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0033_optionmenu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menufood',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
