# Generated by Django 5.1.5 on 2025-05-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0034_alter_menufood_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menufood',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
