# Generated by Django 5.1.5 on 2025-05-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0035_alter_menufood_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menufood',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
