# Generated by Django 5.1.5 on 2025-05-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrabFood', '0036_alter_menufood_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionmenu',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
